---
- name: install nginx
  apt: name=nginx state=present
  become: true
  when: ansible_os_family == "Debian"

- name: install nginx
  yum: name=nginx state=present
  become: true
  when: ansible_os_family == "RedHat"
- name: start nginx
  service: name=nginx state=started
  become: true