---
- name: install nginx on ubuntu
  hosts: webservers
  become: true
  become_user: root
  tasks:
    - name: install nginx
      apt: name=nginx state=present
      become: true
      when: ansible_os_family == "Debian"
    - name: install nginx
      yum: name=nginx state=present
      become: true
      when: ansible_os_family == "RedHat"
    - name: start nginx
      service: name=nginx state=started
      become: true
      
    # - name: install docker
    #   include_role:
    #     name: docker

  roles:
    - docker

#  ansible all -i inventory.yml -m yum -a "name=nginx state=absent" --become

# - name: install nginx on centos
#   hosts: host2
#   become: true
#   become_user: root
#   tasks:
#     - name: install nginx
#       yum: name=nginx state=present
#       become: true
#     - name: start nginx
#       service: name=nginx state=started
#       become: true  